### ISSUE TITLE
[KK] [NodesConstraints] An issue where a timeline scene containing nodes created in v.1.2.1 behaves abnormally when played in v.1.2.2 or higher.

### ISSUE THREAD

**Issue by PoorEnmity** [IllusionMods/HSPlugins#54] opened 2024-01-21 02:48 UTC
https://mega.nz/file/OhBwTajK#Lrxr3IScjnlyE2fCnjhMxvAvjKiq1Im_NAQ4QRO_GMM
⇧⇧⇧ Sample scene used for testing ⇧⇧⇧

https://mega.nz/file/zoBHGKYD#fMIUiowtu_vOsWluJio4ZbF2g46Xo47KMEmKKu6dcUY
⇧⇧⇧ When playing the sample scene in a studio with NodesConstraints v.1.2.1 applied ⇧⇧⇧

https://mega.nz/file/ahhSkKoK#41onb6I-RtEUeYYd8hJK7Hi2MSjWUNGQTrpeSWZnMGc
⇧⇧⇧ When playing the sample scene in a studio with NodesConstraints v.1.2.2 applied ⇧⇧⇧

https://mega.nz/file/ypJiWChS#C-dOMGS7Rb49z7SbE2J-7Tkyv_l2CP_6aceoD74FIps
⇧⇧⇧ When playing the sample scene in a studio with NodesConstraints v.1.2.3 applied ⇧⇧⇧

As you can see in the video, the way objects that depend on cf_j_tang work seems to be completely different between v.1.2.1 and v.1.2.2 or higher. Is this an intended specification? or is it a bug?

Since this is an English sentence written through a translator, what I want to say may not be conveyed properly.

**Comment by takahiro0327** [comment] 2024-01-24 02:43
@PoorEnmity 
Hello.
I've fixed a bug and was wondering if you could try it in your environment. Some people seem to get it and some don't.
If you try it, be sure to let me know the result.

Let me know if you don't know how to handle the DLLs.
This is a bug caused by the timeline working, so please overwrite the DLLs for both NodesConstraints and Timeline.

[KKS_Timeline_NodesConstraints.zip](https://github.com/IllusionMods/HSPlugins/files/14031942/KKS_Timeline_NodesConstraints.zip)
[KK_Timeline_NodesConstraints.zip](https://github.com/IllusionMods/HSPlugins/files/14031948/KK_Timeline_NodesConstraints.zip)

**Comment by PoorEnmity** [comment] 2024-01-24 11:16
I never thought I would be testing a plugin with bugs fixed so quickly, so thank you so much.
After applying the plugin you uploaded, I tested it on the scene where the problem occurred.
The problem that occurred in v.1.2.2 or higher no longer occurs and works the same way as v.1.2.1.

**Comment by takahiro0327** [comment] 2024-01-24 11:19
@PoorEnmity 
Thanks for trying!
Can I have the output_log.txt if you don't mind?
I need a sample.

**Comment by PoorEnmity** [comment] 2024-01-24 11:49
[output_log.txt](https://github.com/IllusionMods/HSPlugins/files/14037642/output_log.txt)

@takahiro0327

I uploaded the output_log.txt generated after running the studio.

I have one suggestion: the newly applied NodesConstraints plugin repeatedly displays the following message in the console, making it inconvenient to check the console.
It would be nice if there was an option to not display this.

[Info: Console] nnnnnnn Expression_LateUpdate_Patches(NodesConstraints)
nnnnnnn Expression_LateUpdate_Patches(NodesConstraints)

**Comment by takahiro0327** [comment] 2024-01-24 11:59
@PoorEnmity
Thanks for the output_log.txt.
Ah, it's a debugging log. It's the version without the following.
Can you also give me the output_log.txt containing the Expression_LateUpdate_Patches?

[KKS_Timeline_NodesConstraints_Without_log.zip](https://github.com/IllusionMods/HSPlugins/files/14037772/KKS_Timeline_NodesConstraints_Without_log.zip)
[KK_Timeline_NodesConstraints_Without_Log.zip](https://github.com/IllusionMods/HSPlugins/files/14037773/KK_Timeline_NodesConstraints_Without_Log.zip)

**Comment by PoorEnmity** [comment] 2024-01-24 12:49
[output_log.txt](https://github.com/IllusionMods/HSPlugins/files/14038467/output_log.txt)

@takahiro0327 
Even though all settings related to log recording are turned on in the BepInEx plugin settings,

[Info: Console] nnnnnnn Expression_LateUpdate_Patches(NodesConstraints)
nnnnnnn Expression_LateUpdate_Patches(NodesConstraints)

This message only appears on the console and doesn't seem to be written to output_log.txt.
Or am I missing something?

![スクリーンショット 2024-01-24 214337](https://github.com/IllusionMods/HSPlugins/assets/157258472/da427f3e-1995-4b26-903b-295e3ed92fb6)

I also confirmed that the message is not displayed after applying the newly uploaded plugin.

**Comment by takahiro0327** [comment] 2024-01-24 13:10
@PoorEnmity 
It's okay. I could see the information I wanted.
Thanks for your help.

**Comment by takahiro0327** [comment] 2024-01-25 01:49
@ManlyMarco 
Please close this one too.

**Closed** 2024-01-25 09:46 UTC
Labels: bug
