### ISSUE TITLE
[KK][NodesConstraints] HF3.29(NodesConstraints1.3.2) and KK_HSPlugins_2024.07.08(NodesConstraints 1.3.3) If you “set as child” the root of a person such as “chaF_001” to something, the person becomes unselectable and CharaStudio is forced to terminate.

### ISSUE THREAD

**Issue by leoftm** [IllusionMods/HSPlugins#83] opened 2024-07-20 09:54 UTC
If you “set as child” the root of a person such as “chaF_001” to something, the person becomes unselectable and CharaStudio is forced to terminate.
It is possible to load the scene and click on the ▶ and ▼ areas without selecting the character, and CharaStudio may not be forced to close just because it becomes unselectable.
If you need to confirm reproducibility, do you need us to upload a video of the procedure?

The version tested is
HF3.29(NodesConstraints1.3.2) and KK_HSPlugins_2024.07.08(NodesConstraints 1.3.3).
I noticed the instability of NodesConstraints in the update from 3.21 to 3.28, I don't think it was there in 3.21.

Sorry for the poor English, I am using a translation engine.

**Comment by ManlyMarco** [comment] 2024-07-20 19:16
Are you absolutely sure that it is caused by NodesConstraints v1.3.3 update? Is the issue fixed by only reverting NodesConstraints to v1.3.2 without changing anything else?

**Comment by ManlyMarco** [comment] 2024-07-20 19:17
Release affected https://github.com/IllusionMods/HSPlugins/releases/tag/r2.13

**Comment by leoftm** [comment] 2024-07-21 01:47
This occurs in both 1.3.2 and 1.3.3.
The version that does not occur is probably in HF3.21.

**Comment by ManlyMarco** [comment] 2024-07-21 07:29
We need to know exactly which version of NC introduced the issue.

**Comment by leoftm** [comment] 2024-07-23 13:39
Sorry, the version of NodesConstraints had nothing to do with it.
It seems that KK_ShalltyUtils and NodesConstraints are conflicting in a scene with complex parent-child relationships.
We confirmed this by removing the plug-ins for the scene causing the problem one by one.
After removing KK_ShalltyUtils, the scene with the parent-child relationship could be reorganized.

... I guess I need to switch to a fix request for .KK_ShalltyUtils, but I don't know how to reproduce the complicated scene situation.
Do I need to upload the scene file and have it checked?
Excuse the POOR English by deepl.

**Comment by ManlyMarco** [comment] 2024-07-23 18:40
You can try asking on discord but at the moment KK_ShalltyUtils is abandoned.

**Comment by leoftm** [comment] 2024-07-24 03:19
ShalltyUtils was very, very convenient for the timeline tool to support numerical input. It's a shame that support is abadon.
And sorry for doubting NodesConstraints. Thanks.
If anyone is having trouble with a similar case (CharaStudio crashes when selecting a parent-child object), it is recommended to try temporarily disabling ShalltyUtils.

**Comment by leoftm** [comment] 2024-07-24 03:28
oh,wait.
https://discord.com/channels/447114928785063977/1091473728740786236/1260153416026689536
ShalltyUtils v1.0 (now) -> v1.1 (2024.07.09)
The above update fixed the crash!
I see that Discord has the latest version, thanks!

**Closed** 2024-07-24 07:58 UTC
